from typing import Protocol, Never
from datetime import timedelta
from result import Either
from boilerplate import UnexpectedError, AuthorizationError
from src.identity.infrastructure.adapters.dto.token import Token, RefreshTokenPayload


class TokenServiceProtocol(Protocol):
    """Defines the contract for token service operations."""

    def generate_token(
        self, user_id: str, token_type: Token, exp: timedelta, jti: str | None = None
    ) -> Either[str, TypeError]: ...

    def create_access_token(
        self, user_id: str, expiry: timedelta = ...
    ) -> Either[str, UnexpectedError]: ...

    def verify_refresh_token(
        self, token: str
    ) -> Either[str, AuthorizationError | UnexpectedError]: ...

    def generate_refresh_key(self, jti: str) -> Either[str, Never]: ...

    def create_refresh_token(
        self, user_id: str, expiry: timedelta = ...
    ) -> Either[str, UnexpectedError]: ...

    def serialize(self, data: dict) -> str: ...

    def deserialize(self, data: str) -> dict: ...

    def hash_token_id(self, jti: str) -> Either[str, Never]: ...
