"""drop expense name column

Revision ID: a6ea987a8bdf
Revises: ad2964c96b65
Create Date: 2026-05-30 04:12:54.298247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ea987a8bdf'
down_revision: Union[str, Sequence[str], None] = 'ad2964c96b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'receipt_url', new_column_name='receipt')
    op.drop_column('expenses', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.alter_column('expenses', 'receipt', new_column_name='receipt_url')
    # ### end Alembic commands ###
